Repository diving-react/study-react-deepdive, pull requests merged in 2024-01, with the labels that each got.

#10 functionBee-chapter1
  chapter01/b.md
Labels: documentation

#13 hyjoong-chapter1
  chapter01/hyjoong.md
Labels: documentation

#24 hyjoong-chapter2
  chapter02/hyjoong.md
Labels: Chapter2

#32 chore: Change templates
  .github/ISSUE_TEMPLATE/♿-accessibility--접근성.md
  .github/ISSUE_TEMPLATE/⛑️-bug--버그.md
  .github/ISSUE_TEMPLATE/🆘-help-wanted--도움-필요.md
  .github/ISSUE_TEMPLATE/🌧️-maintenance--유지보수.md
  .github/ISSUE_TEMPLATE/🌱-good-first-issue--첫-번째-좋은-이슈.md
  .github/ISSUE_TEMPLATE/💪-feature-request--기능-요청.md
  .github/ISSUE_TEMPLATE/🚒-performance-issue--성능-이슈.md
  .github/ISSUE_TEMPLATE/🦾-enhancement--개선.md
  .github/ISSUE_TEMPLATE/🧩-ui--사용자-인터페이스.md
Labels: wontfix

#35 functionBee-chapter3
  .github/pull_request_template.md
  chapter03/b.md
  chapter03/info.md
  examples/chapter03/usState.jsx
  examples/chapter03/useEffect-1.jsx
  examples/chapter03/useEffect-10.tsx
  examples/chapter03/useEffect-11.jsx
  examples/chapter03/useEffect-12.jsx
  examples/chapter03/useEffect-13.tsx
  examples/chapter03/useEffect-14.jsx
  examples/chapter03/useEffect-15.jsx
  examples/chapter03/useEffect-2.jsx
  examples/chapter03/useEffect-3.jsx
  examples/chapter03/useEffect-4.jsx
  examples/chapter03/useEffect-5.jsx
  examples/chapter03/useEffect-6.jsx
  examples/chapter03/useEffect-7.jsx
  examples/chapter03/useEffect-8.jsx
  examples/chapter03/useEffect-9.jsx
Labels: chapter3

#38 hyjoong-chapter3
  chapter03/hyjoong.md
Labels: chapter3

#56 hyjoong-chapter04
  chapter04/hyjoong.md
Labels: Chapter4

#21 JungHun98-chapter2
  chapter02/JungHun.md.md
Labels: Chapter2

#36 docs: JungHun98-chapter3
  chapter03/JungHun98.md.md
Labels: Chapter3

#57 JungHun98-chapter4
  chapter04/JungHun98.md
Labels: Chapter4

#65 hyjoong-chapter11
  chapter11/hyjoong.md
Labels: Chapter11

#26 hyeok999-chapter2
  chapter02/hyeok999.md
Labels: Chapter2

#68 JungHun98-chapter11
  chapter11/JungHun-98.md
Labels: Chapter11
